[build]
  base = "faar"
  command = "npm run build"
  publish = "dist"  # Changed from "faar/dist"

[[redirects]]
  from = "/*"
  to = "/faar/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"